P5\Model\User:
    properties:
        email:
            - NotBlank: ~
            - Email:
                message: The email "{{ value }}" is not a valid email.
                groups:
                    - admin_edit_user
        username:
            - NotBlank: ~