admin:
    resource: "@AdminBundle/Controller"
    prefix:   /admin
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
